# Generated by Django 2.2.5 on 2019-09-08 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20190908_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussione',
            name='autore_discussione',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussioni', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discussione',
            name='sezione_appartenenza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sezioni', to='forum.Sezione'),
        ),
    ]
